### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by R3str** [R3str/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Other-account** [comment]
I love to be at one with nature. Therefore, I travel my whole life. I am like a wandering warrior who gets better and better in martial arts every day, I have no time to rest. Workouts, workouts and more workouts! The only this way!
Many people say that I have a bad sense of humor, but this is not at all true, it's just that they are stupid ape-like people and do not understand the pinnacle of true humor.
I'm also a fan of Captain America, Spider-Man and Cyclops. He-he =)

**Comment by R3str** [comment]
It`s awesome! Thx xD
